# Generated by Django 4.2.7 on 2024-12-04 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workorder",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Work Order",
                "verbose_name_plural": "Work Orders",
            },
        ),
        migrations.AddField(
            model_name="workorder",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="cost_per_unit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_orders",
                to="manufacturing.product",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="workstation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_orders",
                to="manufacturing.workstation",
            ),
        ),
    ]
