# Generated by Django 4.2.7 on 2024-12-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0002_alter_workorder_options_workorder_notes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workorder",
            options={
                "ordering": ["-priority", "-created_at"],
                "verbose_name": "Work Order",
                "verbose_name_plural": "Work Orders",
            },
        ),
        migrations.AddField(
            model_name="workorder",
            name="blocking_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="dependent_orders",
                to="manufacturing.workorder",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low Priority"),
                    ("MEDIUM", "Medium Priority"),
                    ("HIGH", "High Priority"),
                    ("CRITICAL", "Critical Priority"),
                ],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("QUEUED", "Queued"),
                    ("READY", "Ready to Start"),
                    ("IN_PROGRESS", "In Progress"),
                    ("PAUSED", "Paused"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("BLOCKED", "Blocked"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
