# Generated by Django 4.2.7 on 2024-12-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0005_productionlog_efficiency_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="current_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="max_stock_level",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="product",
            name="restock_level",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_status",
            field=models.CharField(
                choices=[
                    ("IN_STOCK", "In Stock"),
                    ("LOW_STOCK", "Low Stock"),
                    ("OUT_OF_STOCK", "Out of Stock"),
                    ("DISCONTINUED", "Discontinued"),
                ],
                default="IN_STOCK",
                max_length=20,
            ),
        ),
    ]
