# Generated by Django 4.2.7 on 2024-12-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manufacturing",
            "0006_product_current_quantity_product_max_stock_level_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workstation",
            name="last_maintenance",
            field=models.DateTimeField(
                blank=True, help_text="Date and time of last maintenance", null=True
            ),
        ),
        migrations.AlterField(
            model_name="workstation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workstation",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("MAINTENANCE", "Maintenance"),
                    ("INACTIVE", "Inactive"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
