# Generated by Django 4.2.7 on 2024-12-09 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0007_workstation_last_maintenance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_reserved",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="manufacturing.material",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_reservations",
                        to="manufacturing.workorder",
                    ),
                ),
            ],
        ),
    ]
