# Generated by Django 4.2.7 on 2024-12-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0010_workstation_efficiency_rate_workstation_hourly_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sell_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Selling price per unit of the product",
                max_digits=10,
            ),
        ),
    ]
