# Generated by Django 4.2.7 on 2024-12-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0011_product_sell_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workstation",
            name="efficiency_rate",
        ),
        migrations.RemoveField(
            model_name="workstation",
            name="hourly_rate",
        ),
        migrations.AlterField(
            model_name="product",
            name="sell_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
