# Generated by Django 4.2.7 on 2024-12-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0010_workstationefficiencymetric"),
        ("manufacturing", "0012_workstation_process_type"),
    ]

    operations = []
