# Generated by Django 4.2.7 on 2024-12-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0012_remove_workstation_efficiency_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="labor_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total labor cost for producing this product",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="material_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total material cost for producing this product",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="overhead_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Overhead costs associated with producing this product",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="profit_margin",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Profit margin percentage",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sell_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Selling price of the product",
                max_digits=10,
            ),
        ),
    ]
