# Generated by Django 4.2.7 on 2024-12-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0013_product_labor_cost_product_material_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="material_cost",
        ),
        migrations.RemoveField(
            model_name="product",
            name="overhead_cost",
        ),
        migrations.RemoveField(
            model_name="product",
            name="profit_margin",
        ),
        migrations.AlterField(
            model_name="product",
            name="sell_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
