# Generated by Django 5.1.4 on 2024-12-14 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0015_workstation_hourly_operating_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Suppliers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typical_lead_time",
                    models.IntegerField(
                        blank=True, help_text="Typical lead time in days", null=True
                    ),
                ),
                (
                    "typical_price_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Typical price per unit of material",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_preferred_supplier", models.BooleanField(default=False)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manufacturing.material",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manufacturing.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Supplier Materials",
                "unique_together": {("supplier", "material")},
            },
        ),
        migrations.AddField(
            model_name="supplier",
            name="materials",
            field=models.ManyToManyField(
                related_name="suppliers",
                through="manufacturing.SupplierMaterial",
                to="manufacturing.material",
            ),
        ),
    ]
